### ISSUE TITLE
How many topics can be subscribed to at most (CA-224)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-aws-iot#123]
I tried to modify CONFIG_AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS=100. Subscribed to a hundred topics, then all returned success, but only the first fifty topics of the release information device to receive.
The chip is esp8266

**Comment by shahpiyushv** [comment]
@shun-dgut , as per the limits specified [here](https://docs.aws.amazon.com/general/latest/gr/iot-core.html), a given client can subscribe only to 50 topics.

**Comment by shun-dgut** [comment]
thank you for your reply.
