### ISSUE TITLE
Guidance on OTA Update on ESP32 via AWS IoT and Platform.IO (CA-236)

### ISSUE THREAD

**Issue by FanuelConrad** [espressif/esp-aws-iot#133]
Hello,
I'd like to be guided on how to perform OTA Update on ESp32 via AWS IoT and Platform.IO
Any response will be highly appreciated

**Comment by LozGMK** [comment]
Have you tried [this](https://github.com/maxgerhardt/pio-espidf-aws-mqtt-ota)?
