### ISSUE TITLE
How to integrate with coreMQTT Agent library (CA-237)

### ISSUE THREAD

**Issue by Gabriel-Gardin** [espressif/esp-aws-iot#134]
Hello,

I really appreciate this component and the examples, however, I would also like to use the coreMQTT Agent library, is there any plan to include it?

The idea of having a dedicated MQTT agent task that manages the MQTT connection in the background is really nice, this way we could use the MQTT as a library, with multiple tasks publishing and receiving messages simultaneously. I am trying to make this integration, but it's not simple.

Thanks in advance.

**Comment by dhavalgujar** [comment]
Hi @Gabriel-Gardin,
The coreMQTT-Agent library is included in the latest release of our port.
You can find it here: [esp-aws-iot/libraries/coreMQTT-Agent](https://github.com/espressif/esp-aws-iot/tree/release/202012.04-LTS/libraries/coreMQTT-Agent)

There is also a reference example that shows how you can use the coreMQTT-Agent library for simple PubSub and OTA, that you can find linked in the README [here](https://github.com/espressif/esp-aws-iot/blob/master/README.md?plain=1#L24).
