### ISSUE TITLE
AWS_IOT_MQTT_TX_BUF_LEN limited to 65536 bytes

### ISSUE THREAD

**Issue by erki1993** [espressif/esp-aws-iot#15]
Why is the KConfig variable AWS_IOT_MQTT_TX_BUF_LEN limited to max 65536 bytes? 

We have a project that requires uploads of ~80000 bytes. 

I tested by editing the esp-aws-iot component and changing the max value to 80000 and I could successfully publish my 76000 bytes of data. I am storing the aws iot client in spiram so there are no concerns with running out of RAM.

 MQTT spec defines max payload as 268,435,456 bytes.
 
config AWS_IOT_MQTT_TX_BUF_LEN
    int "MQTT TX Buffer Length"
    default 512
    range 32 **65536**
    help
        Maximum MQTT transmit buffer size. This is the maximum MQTT
        message length (including protocol overhead) which can be sent.

        Sending longer messages will fail.

**Comment by shahpiyushv** [comment]
@erki1993 , changed it to 128K (131072 bytes) as that is that max allowed by AWS IoT as per https://docs.aws.amazon.com/iot/latest/developerguide/limits-iot.html.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been addressed.

**Comment by dizcza** [comment]
@erki1993 could you share the code for publishing such a large (binary) payload to AWS IoT with ESP32?
thanks
