### ISSUE TITLE
could you please provide fleet_provisioning example ? (CA-254)

### ISSUE THREAD

**Issue by yucelz** [espressif/esp-aws-iot#150]
I tried many different ways to create fleet_provisioning based on the aws-iot-device-sdk-embedded-C but couldn't figure out. The libraries' version doesn't match and caused lots of exceptions.

https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/fleet_provisioning/fleet_provisioning_with_csr

**Comment by SolidStateLEDLighting** [comment]
Fleet provisioning is all about subscriptions and publishing to topics -- then handling the responses.   One of the ugly parts of the work is in reformating the provided keys into the correct form.   The keys will be sent to you with 2-character printable line feeds "/n" and you'll need to change those out to non-printable line feeds (the ones you just see in action on the screen).

Other than this -- fleet provision is just messaging -- and of course the correct roles, certificates, and template at AWS.   I did my project using provisioning by claim.   I never figured out how to do this with the certificate signing request (csr).
