### ISSUE TITLE
aws-iot last will (IDFGH-644) (CA-10)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-aws-iot#16]
I am fighting for some time with aws-iot last will. When i set plain text in last will there is no issue, but when i am trying to set simple json string then most of the time data is corrupted. Usually its missing 1 or 2 leading chars or sometimes leading bytes (1-2) are replaced with other random char.
I could add leading space if not the problem that sometimes 2 chars are corrupted and in very rare case there is no corruption in string.

Any advice or help will be appreciated because its in production app.

**Comment by mahavirj** [comment]
Sorry I did not look into this further as we didn't reach to any conclusion if this issue was in AWS IoT SDK or ESP32 port. But since you had working settings, I believe we can close it. Please feel free to re-open if we need more investigations.
