### ISSUE TITLE
Enabling esp secure cert cause firmware unable to compile (CA-335)

### ISSUE THREAD

**Issue by anuarrozman** [espressif/esp-aws-iot#220]
### Enabling esp secure cert cause firmware unable to compile

Hi, Im having some issues when enabling esp secure cert for my aws mqtt. During compilation it shows (screenshot below). 

![image](https://github.com/espressif/esp-aws-iot/assets/133958238/a576e981-c114-42b2-9760-c4213378c53e)

**Comment by kvp1703** [comment]
Hi @anuarrozman, based on the screenshot, it looks like you're facing issue with your custom application when you enable secure partition.
We could not reproduce it with the tls_mutual_auth example application (by enabling secure cert related configuration). 
In most scenarios, the error of missing parenthesis appears when the preceding code either has unterminated parenthesis or some extra parenthesis. Regardless, could you help with a few things to better debug this:

1. If you could help provide some code snippet atop an example application to reproduce the issue at our end?
2. Just for the sake of completion, kindly provide version of esp-aws-iot and esp-idf you are on.
