### ISSUE TITLE
undefined reference to "FUNCTION"

### ISSUE THREAD

**Issue by wltn928** [espressif/esp-aws-iot#4]
Hi,

I am trying to integrate thing_shadow and ble_prov(in esp-idf/example)
( set wifi with ble_prov -> shadow_get )

Add
`#include <esp_bt.h>`
and make command there are problems like below
![image](https://user-images.githubusercontent.com/34079247/57436314-66ee9880-727a-11e9-958b-52a13426e261.png)

It looks like it doesn't refer to a function due to a library problem.
Can I link library??

Thanks to read!! 
best regards.

**Comment by mahavirj** [comment]
@wltn928 Have you enabled `Bluetooth` from configuration option (`CONFIG_BT_ENABLED=y` have this line in your sdkconfig)?

**Comment by wltn928** [comment]
@mahavirj 
I honestly respect you.
Thanks for help!!
