### ISSUE TITLE
E (4760) aws_iot: failed! mbedtls_net_connect returned -0x52 (CA-109)

### ISSUE THREAD

**Issue by isaurabhpawar** [espressif/esp-aws-iot#42]
ESP32 with AWS_IOT is running but giving me this error

"E (4760) aws_iot: failed! mbedtls_net_connect returned -0x52"

followed all the step

**Comment by shahpiyushv** [comment]
@isaurabhpawar , can you double check that the AWS IOT MQTT host and the port are configured correctly and also reachable from your network?

**Comment by isaurabhpawar** [comment]
Thankyou! It worked 
Tried changing port !

**Comment by PaulAnurag** [comment]
Hi @isaurabhpawar , I know  its been a long time, but Did you try changing port in the sdkconfig?
