### ISSUE TITLE
Shadow Update timeout error if delay is increased in while loop (CA-112)

### ISSUE THREAD

**Issue by anubhav1** [espressif/esp-aws-iot#44]
I was testing the` thing_shadow_example.c` and found out that increasing delay to 4 sec. `vTaskDelay(4000 / portTICK_RATE_MS); `in while loop causing a shadow update timeout error. Is it an expected behavior? 
What is the explanation of this behavior?

**Comment by shahpiyushv** [comment]
The shadow update call in the example is this:

``` 
 rc = aws_iot_shadow_update(&mqttClient, CONFIG_AWS_EXAMPLE_THING_NAME, JsonDocumentBuffer,
                                               ShadowUpdateStatusCallback, NULL, 4, true);
```

Here, it means that the shadow update response is expected within 4 seconds (second last argument). If you have a delay of 4 seconds, you are bound to miss this timing requirement. You may try setting the timeout in `aws_iot_shadow_update()` to 6 seconds.
