### ISSUE TITLE
aws-iot-device-sdk-embedded-C 2021xx.xx support in esp idf v4.2 (CA-126)

### ISSUE THREAD

**Issue by rmshub** [espressif/esp-aws-iot#47]
Hi Team,

I'm looking for IOT jobs for OTA updates. This feature are introduced in newer aws-iot-device-sdk-embedded-C.
Will be there support for latest aws-iot-device-sdk-embedded-C as esp-idf component

**Comment by rmshub** [comment]
Hi Team,

Is info on this request?

**Comment by samuelbles07** [comment]
I guess this project is discontinued?

**Comment by shahpiyushv** [comment]
We are working on adding the required pieces one by one, starting with plain publish/subscribe followed by thing-shadow and later OTA, Jobs, etc. You may expect updates to this repo starting next week.

**Comment by rmshub** [comment]
Thanks for update

**Comment by Prabhuelectro** [comment]
@shahpiyushv no updates, now it is august.

**Comment by shahpiyushv** [comment]
@Prabhuelectro @rmshub , sorry we did not update here, but as you can see in my comment [here](https://github.com/espressif/esp-aws-iot/issues/53#issuecomment-880927892), beta releases for the same are already available.  You may expect further updates on this in a day or two.

**Comment by rmshub** [comment]
When will be esp-aws-iot beta version turned to stable release.

**Comment by rmshub** [comment]
Any update on this topic ?

**Comment by rmshub** [comment]
Any update on this topic ?

**Comment by jeffxor** [comment]
Any update on this? Is this project discontinued?

No commits for 9 months and using a library that is over 2 years old. When can we expect some updates?
