### ISSUE TITLE
Can you support ESP8266?

### ISSUE THREAD

**Issue by wzbhbb** [espressif/esp-aws-iot#8]
Hi, 
i want to know whether this framework support ESP8266?
https://github.com/espressif/ESP8266_RTOS_SDK

**Comment by shahpiyushv** [comment]
@wzbhbb The ESP8266 RTOS SDK has aws-iot as a committed component (https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/components/aws_iot).

The esp-aws-iot is currently expected to be used only with ESP32 (ESP IDF). Going ahead, we may add support for ESP8266 here, but as of now, there is no immediate plan for that.

**Comment by wzbhbb** [comment]
Thanks you
