### ISSUE TITLE
OTA Agent stopped Causes an ESP reboot (Guru Meditation Error) (CA-183)

### ISSUE THREAD

**Issue by EmbeddedDBL** [espressif/esp-aws-iot#88]
I work with the ota example since they released this version everything has been working fine for my development, lately I've been getting an unexpected reboot of the ESP device just before trying to stop the OTA Agent and the demo. Since I use this demo to provide OTA update to a second processor.

I debug this problem but I don't have a certainty of the problem

Monitor failure log image
idf version: 4.2

![Log_FAIL2_AWS](https://user-images.githubusercontent.com/94095787/149572644-096c795e-2eb0-4f04-8dfd-bf30c17c1fc9.PNG)

**Comment by SolidStateLEDLighting** [comment]
I noticed that you're subscribing and unsubscribing to a stream with no streamId.   That Id would have been obtained previously with a call for a job description.    Make sure you check-box the MQTT protocol option when you set up the OTA job.   I check both HTTP and MQTT and I get all the info even though I don't use the HTTP portion of it.
