### ISSUE TITLE
ota example download  (CA-192)

### ISSUE THREAD

**Issue by git4gaurav** [espressif/esp-aws-iot#96]
Hi,
the ota mqtt demo for aws meant for esp32 was downloaded from :
https://github.com/espressif/esp-aws-iot/tree/release/beta/examples/ota/ota_mqtt

Steps use to download project files were: 
1. download .zip file from:
https://github.com/espressif/esp-aws-iot/tree/release/beta
2. Download libraries using:
git clone --recurse-submodules https://github.com/aws/aws-iot-device-sdk-embedded-C.git

following are the issues faced:
a. there is no clone link for ota mqtt demo
b. when .zip is downloaded, library/ sdk files are missing

Please check attached file having error log on build. Pl. suggest if file download steps are ok and help in resolving build errors.
Problem window image is shown below:
![image](https://user-images.githubusercontent.com/98801591/154910111-8af12497-148a-413b-9126-5fe1da2d705b.png)

**Comment by shahpiyushv** [comment]
@git4gaurav , if you download the repository as a zip, the git commands, including `git submodule update --init --recursive` would not work. I suppose you may have got some error like `fatal: not a git repository (or any of the parent directories): .git`. Please download using `git clone --recursive -b release/beta https://github.com/espressif/esp-aws-iot`

**Comment by git4gaurav** [comment]
Hi, below error image is shown... 
![image](https://user-images.githubusercontent.com/98801591/155188278-5ec736be-7746-420c-9e8b-86bfbeb41161.png)
pl. let me know, what should be done to resolve above

**Comment by dhavalgujar** [comment]
> and when device changed in edit to esp32-c3....then below is the error: Description Resource Path Location Type fatal error: soc/dport_reg.h: No such file or directory esp32-c3-ota line 37, external location: C:\esp-idf\components\ota-esp32c3\esp-aws-iot\port\ota\aws_esp_ota_ops.c C/C++ Problem
> 
> What are necessary configurations required in config aprt from WiFi
> 
> Please guide on this.

Can you please try the patch mentioned [here](https://github.com/espressif/esp-aws-iot/issues/99#issuecomment-1049100846) and confirm if it fixes it for you?
This will be fixed in the port shortly.

**Comment by git4gaurav** [comment]
Thanks shahpiyushv and dhavalgujar. I was able to run demo.
